#!/bin/sh

set -e

if [ "$1" = "1" ]; then
    FIRSTTIMEINSTALL=1
fi

if [ "$FIRSTTIMEINSTALL" = "1" ]; then
    # Generate apache2 vhost based on the config.env.m4 template file
    m4 /etc/packaged-site/@PACKAGENAME@/config.@ENV@.m4 /etc/packaged-site/@PACKAGENAME@/apache2.conf > /etc/httpd/conf.d/002-@PACKAGENAME@.conf
    apache2ctl graceful
fi

echo "Installation of @PACKAGENAME@ finished !"
echo "To finish setting up your project you need to copy the file
/var/www/@PACKAGENAME@/config.php.dist to /var/www/@PACKAGENAME@/config.php
and fill in the database parameters"
